[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pancalc-tools"
version = "0.1.1"
description = "Package manager and developer toolkit for Casio Prizm calculators"
readme = "README.md"
license = { text = "PAN DEVS NON-COMMERCIAL ATTRIBUTION LICENSE v1.0" }
authors = [{ name = "Pan Devs", email = "pan.devs@proton.me" }]
requires-python = ">=3.10"
keywords = ["casio", "prizm", "fx-cg50", "calculator", "package-manager"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Hardware",
]
dependencies = [
    "click>=8.1",
    "rich>=13.0",
    "questionary>=2.0",
    "requests>=2.31",
    "Pillow>=10.0",
    "pymupdf>=1.23",
    "platformdirs>=4.0",
    "textual>=8.2.7",
    "python-gnupg>=0.5.0",
]

[project.scripts]
pcalc = "pcalc.cli:cli"

[tool.setuptools.packages.find]
include = ["pcalc*"]

[project.optional-dependencies]
windows = ["pywin32"]